# Generated by Django 6.0 on 2026-01-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('cadastro', 'Cadastro'), ('edicao', 'Edição'), ('exclusao', 'Exclusão'), ('visualizacao', 'Visualização'), ('download', 'Download'), ('upload', 'Upload'), ('outro', 'Outro')], max_length=50, verbose_name='Ação')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Atividade Recente',
                'verbose_name_plural': 'Atividades Recentes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exibir_atividades_recentes', models.BooleanField(default=True, verbose_name='Exibir Atividades Recentes')),
                ('exibir_notificacoes', models.BooleanField(default=True, verbose_name='Exibir Notificações')),
                ('exibir_estatisticas', models.BooleanField(default=True, verbose_name='Exibir Estatísticas')),
                ('exibir_atalhos', models.BooleanField(default=True, verbose_name='Exibir Atalhos Rápidos')),
                ('itens_por_pagina', models.IntegerField(default=10, verbose_name='Itens por Página')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('auto', 'Automático')], default='auto', max_length=20, verbose_name='Tema')),
                ('notificacoes_email', models.BooleanField(default=True, verbose_name='Receber Notificações por E-mail')),
                ('notificacoes_push', models.BooleanField(default=False, verbose_name='Receber Notificações Push')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_dashboard', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Configuração do Dashboard',
                'verbose_name_plural': 'Configurações do Dashboard',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro'), ('sistema', 'Sistema')], default='info', max_length=20, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('link', models.CharField(blank=True, help_text='URL para ação relacionada', max_length=500, verbose_name='Link')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MenuFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fa-home)', max_length=50, verbose_name='Ícone')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Menu Favorito',
                'verbose_name_plural': 'Menus Favoritos',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('perfil', 'url')},
            },
        ),
    ]
