# Generated by Django 6.0 on 2026-01-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletivos', '0001_initial'),
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='coletivo_padrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='coletivos.coletivo', verbose_name='Coletivo Padrinho'),
        ),
    ]
