# Generated by Django 6.0 on 2026-01-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_institucional', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('responsavel_legal', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo_usuario': 'COLETIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='dados_coletivo', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Coletivo Institucional',
                'verbose_name_plural': 'Coletivos Institucionais',
            },
        ),
    ]
