# Generated by Django 6.0 on 2026-01-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Telefone Alternativo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('area_atuacao', models.CharField(blank=True, max_length=100, verbose_name='Área de Atuação')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, verbose_name='Tipo de Conta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo_usuario': 'AFILIADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='dados_afiliado', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ContratoAfiliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Comissão (%)')),
                ('termo_aceito', models.BooleanField(default=False, verbose_name='Termo Aceito')),
                ('data_aceite', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite')),
                ('ip_aceite', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Aceite')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='afiliados.afiliado')),
            ],
            options={
                'verbose_name': 'Contrato de Afiliação',
                'verbose_name_plural': 'Contratos de Afiliação',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
