# Generated by Django 6.0 on 2026-01-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='perfis.perfil'),
        ),
    ]
