# Generated by Django 6.0 on 2026-01-15 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_perfil'),
        ('perfis', '0003_perfil_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_contato',
            field=models.EmailField(max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=150, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='perfis.perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site/URL'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
