# Generated by Django 6.0 on 2026-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_options_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(default='', max_length=255, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default='', max_length=20, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
